name: "Issue Report | In [option name]"
description: Create a report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue and helping us improve **VanishRaider**!
  - type: textarea
    id: description
    attributes:
      label: What is your problem?
      description: Provide a clear description of your issue/bug.
      placeholder: "Vanish is Instantly closing.."
    validations:
      required: true
  - type: textarea
    id: frequency
    attributes:
      label: Frequency of Occurrence
      description: How often does this issue occur? (e.g., always, sometimes, rarely)
      placeholder: "Always"
  - type: textarea
    id: screenshots
    attributes:
      label: Attach Screenshot (Optional)
      description: If you can, please upload an image of issue.
