name: "Issue Report | In [option name]"
description: Create a report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue and helping us improve VanishRaider!.
  - type: textarea
    id: description
    attributes:
      label: What is your problem?
      description: Provide a clear description of your issue/bug
    validations:
      required: true
