name: "[Issue] Name Here"
description: Create a report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue and helping us improve **VanishRaider**!
  - type: textarea
    id: description
    attributes:
      label: What is your problem?
      description: Provide a clear description of your issue/bug.
      placeholder: "Vanish is Instantly closing.."
    validations:
      required: true
  - type: textarea
    id: frequency
    attributes:
      label: Frequency
      description: How often does this issue happen? (e.g, always, sometimes, rarely)
      placeholder: "Always"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Attach Screenshot (Optional)
      description: If you can, please upload an image of issue.
  - type: checkboxes
    id: terms
    attributes:
      label: Vanish Wiki
      description: before submitting Read our [wiki](https://github.com/vanishgg/VanishRaider/wiki). 
      options:
        - label: Have You read vanish wiki?
          required: true
