name: "Feature request"
description: Suggest a new feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for Suggesting something and helping us improve **VanishRaider**!
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Additional context
      description: Add any other context or example screenshots(if you can) about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: priority
      description: Enter a priority level you think is right for this feature, if its not i will either delete or dismiss most likely 
      options:
        - label: Low
        - label: High
        - label: Top
          required: true
