name: "Feature request"
description: Suggest a new feature
assignees:
  - vanishgg
body:
  - type: markdown
    attributes:
      value: |
        Thank you for Suggesting something and helping us improve **VanishRaider**!
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: description2
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: description3
    attributes:
      label: Additional context
      description: Add any other context or example screenshots(if you can) about the feature request here.
  - type: checkboxes
    id: priority
    attributes:
      label: Priority
      description: Enter a priority level you think is right for this feature. If it's not correct, I will either delete or dismiss it, most likely.
      options:
        - label: Low
        - label: High
        - label: Top
    validations:
      required: true
